version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  db:
    image : mysql
    container_name : mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3310:3310"
    environment:
      MYSQL_DATABASE: db_marek_kukulski
      MYSQL_ROOT_PASSWORD: password

  app:
    container_name: app
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - db
